version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - marketing_solution_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - marketing_solution_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - marketing_solution_network
    volumes:
      - grafana_data:/var/lib/grafana

  mautic:
    image: mautic/mautic:latest
    container_name: mautic
    restart: always
    ports:
      - '8090:80'
    environment:
      - MAUTIC_DB_HOST=postgres
      - MAUTIC_DB_NAME=${POSTGRES_DB}
      - MAUTIC_DB_USER=${POSTGRES_USER}
      - MAUTIC_DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - marketing_solution_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
    networks:
      - marketing_solution_network

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - '8080:80'
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - marketing_solution_network

  rasa:
    image: rasa/rasa:latest-full
    container_name: rasa
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - ./rasa_bot:/app
    command:
      - run
      - --enable-api
    networks:
      - marketing_solution_network

  scrapy:
    build: ./scrapy_project
    image: scrapy_bot
    container_name: scrapy
    restart: always
    networks:
      - marketing_solution_network

networks:
  marketing_solution_network:

volumes:
  postgres_data:
  portainer_data:
  grafana_data:
  nextcloud_data:
